!INCLUDE		$(SVRHOME)\makent.env

CFLAGS = \
	/D "_CONSOLE" /D "_MBCS" \
	/I $(COMMON)\include \
	$(CFOPT)

HEADER = \
	$(COMMON)\include\cbuni.h

DLIBS = \

LIBS = \
	$(LSYS)

OBJS =  \
	$(INTDIR)\fstr.obj	

all	: echo $(RUNNT)\bin\fstr.exe

echo	:
	@echo	HYPUB/UTILSRC/FSTR

$(RUNNT)\bin\fstr.exe	: $(OBJS) $(DLIBS)
	$(LINK) /out:"$@" /subsystem:console $(LDOPT) $(OBJS) $(LIBS)

$(INTDIR)\fstr.obj	: fstr.c $(HEADER)
	$(CC) /Fo"$@" $(CFLAGS) /c fstr.c


