#!/bin/sh
# program compile
#

#main
	Param=$1
	case "$Param" in
		c)			COMP_TARGET=$2; export COMP_TARGET
					make -f Makefile.c;;
		pc)			COMP_TARGET=$2; export COMP_TARGET
					make -f Makefile.pc;;
		clean)		make -f Makefile.pc clean;;
		*)			echo "Usage: $0 argument";;
	esac
