!INCLUDE		$(SVRHOME)\makent.env

CFLAGS = \
	/D "_CONSOLE" /D "_MBCS" \
	/I $(COMMON)\include \
	$(CFOPT)

HEADER = \
	$(COMMON)\include\cbuni.h

DLIBS =

LIBS = \
	$(LSYS)

OBJS =  \
	$(INTDIR)\dwc.obj	

all	: echo $(RUNNT)\bin\dwc.exe

echo	:
	@echo	HYPUB/UTILSRC/DWC

$(RUNNT)\bin\dwc.exe	: $(OBJS) $(DLIBS)
	$(LINK) /out:"$@" /subsystem:console $(LDOPT) $(OBJS) $(LIBS)

$(INTDIR)\dwc.obj	: dwc.c $(HEADER)
	$(CC) /Fo"$@" $(CFLAGS) /c dwc.c


