!INCLUDE		$(SVRHOME)\makent.env

CFLAGS = \
	/D "_CONSOLE" /D "_MBCS" \
	/I $(COMMON)\include \
	$(CFOPT)

HEADER = \
	$(COMMON)\include\cbuni.h \
	$(COMMON)\include\ipcwrap.h

DLIBS = \
	$(RUNNT)\lib\ipcwrap.lib

LIBS = \
	$(RUNNT)\lib\ipcwrap.lib \
	$(LSYS)

OBJS =  \
	$(INTDIR)\showshm.obj	

all	: echo $(RUNNT)\bin\showshm.exe

echo	:
	@echo	HYPUB/UTILSRC/SHOWSHM

$(RUNNT)\bin\showshm.exe	: $(OBJS) $(DLIBS)
	$(LINK) /out:"$@" /subsystem:console $(LDOPT) $(OBJS) $(LIBS)

$(INTDIR)\showshm.obj	: showshm.c $(HEADER)
	$(CC) /Fo"$@" $(CFLAGS) /c showshm.c


