!INCLUDE		$(SVRHOME)\makent.env

CFLAGS = \
	/D "_CONSOLE" /D "_MBCS" \
	/I $(COMMON)\include \
	$(CFOPT)

HEADER = \
	$(COMMON)\include\cbuni.h \
	$(COMMON)\include\iswrap.h \
	$(COMMON)\include\gps.h \
	$(COMMON)\include\pisam.h \
	$(COMMON)\include\dsml.h

DLIBS = \
	$(RUNNT)\lib\disam32.lib \
	$(RUNNT)\lib\gps.lib \
	$(RUNNT)\lib\pisam.lib \
	$(RUNNT)\lib\dsml.lib

LIBS = \
	$(RUNNT)\lib\disam32.lib \
	$(RUNNT)\lib\gps.lib \
	$(RUNNT)\lib\pisam.lib \
	$(RUNNT)\lib\dsml.lib \
	$(LSYS)

OBJS =  \
	$(INTDIR)\dsml2tst.obj	

all	: echo $(INTDIR)\dsml2tst.exe

echo	:
	@echo	HYPUB/TESTSRC/DSML2TST

$(INTDIR)\dsml2tst.exe	: $(OBJS) $(DLIBS)
	$(LINK) /out:"$@" /subsystem:console $(LDOPT) $(OBJS) $(LIBS)

$(INTDIR)\dsml2tst.obj	: dsml2tst.c $(HEADER)
	$(CC) /Fo"$@" $(CFLAGS) /c dsml2tst.c


