!INCLUDE		$(SVRHOME)\makent.env

CFLAGS = \
	/D "_CONSOLE" /D "_MBCS" \
	/I $(COMMON)\include \
	$(CFOPT)

HEADER = \
	$(COMMON)\include\cbuni.h \
	$(COMMON)\include\gps.h \
	$(COMMON)\include\pisam.h \
	$(COMMON)\include\dsml.h

DLIBS = \
	$(RUNNT)\lib\disam32.lib \
	$(RUNNT)\lib\gps.lib \
	$(RUNNT)\lib\pisam.lib \
	$(RUNNT)\lib\dsml.lib 

LIBS = \
	$(RUNNT)\lib\disam32.lib \
	$(RUNNT)\lib\gps.lib \
	$(RUNNT)\lib\pisam.lib \
	$(RUNNT)\lib\dsml.lib  \
	$(LSYS)

OBJS =  \
	$(INTDIR)\dsmladm.obj	

all	: echo $(RUNNT)\bin\dsmladm.exe

echo	:
	@echo	HYPUB/UTILSRC/DSMLADM

$(RUNNT)\bin\dsmladm.exe	: $(OBJS) $(DLIBS)
	$(LINK) /out:"$@" /subsystem:console $(LDOPT) $(OBJS) $(LIBS)

$(INTDIR)\dsmladm.obj	: dsmladm.c $(HEADER)
	$(CC) /Fo"$@" $(CFLAGS) /c dsmladm.c


